"""Initial migration sqlite

Revision ID: ee7062859214
Revises: 
Create Date: 2025-12-19 12:31:21.237996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee7062859214'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('town', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('house_type', sa.Enum('DUPLEX', 'DETACHED_DUPLEX', 'SEMI_DETACHED_DUPLEX', 'MODERN_DETACHED', 'BUNGALOW', 'APARTMENT', 'TERRACE', 'PENTHOUSE', name='housetype'), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Enum('ONE', 'TWO', 'THREE', 'FOUR', 'FIVE_PLUS', name='bathroomtype'), nullable=False),
    sa.Column('toilets', sa.Enum('ONE', 'TWO', 'THREE', 'FOUR', 'FIVE_PLUS', name='toilettype'), nullable=False),
    sa.Column('parking_space', sa.Enum('ONE', 'TWO', 'THREE', 'FOUR_PLUS', name='parkingspacetype'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_houses_house_type'), 'houses', ['house_type'], unique=False)
    op.create_index(op.f('ix_houses_id'), 'houses', ['id'], unique=False)
    op.create_index(op.f('ix_houses_price'), 'houses', ['price'], unique=False)
    op.create_index(op.f('ix_houses_state'), 'houses', ['state'], unique=False)
    op.create_index(op.f('ix_houses_town'), 'houses', ['town'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_houses_town'), table_name='houses')
    op.drop_index(op.f('ix_houses_state'), table_name='houses')
    op.drop_index(op.f('ix_houses_price'), table_name='houses')
    op.drop_index(op.f('ix_houses_id'), table_name='houses')
    op.drop_index(op.f('ix_houses_house_type'), table_name='houses')
    op.drop_table('houses')
    # ### end Alembic commands ###
